name: flutter_app_astronomy
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cached_network_image: ^3.2.1
  camera: ^0.10.5+5
  cupertino_icons: ^1.0.5
  easy_image_viewer: ^1.2.1
  extended_image: ^8.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_nav_bar: ^5.0.6
  image_picker: ^1.0.4
  line_icons: ^2.0.3
  path_provider: ^2.1.1
  shaky_animated_listview: ^0.0.5
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
